name: C++ CI

on:
  push:
    branches:
      - J3113_Konkova_Nina
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++

    - name: Set execute permissions
      run: chmod +x ./cmake-build-debug/PolygonLabelEncoderTests.exe

    - name: Run PolygonLabelEncoderTests
      run: ./cmake-build-debug/PolygonLabelEncoderTests.exe  