name: C++ CI

on:
  push:
    branches:
      - J3113_Konkova_Nina
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          submodules: true

    - name: Install CMake
      run: |
        Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-windows-x86_64.msi" -OutFile cmake.msi
        Start-Process msiexec.exe -ArgumentList '/i cmake.msi /quiet /norestart' -NoNewWindow -Wait
        Remove-Item cmake.msi

        
    - name: Configure CMake
      run: |
        cmake -S . -B cmake-build-debug -G "Visual Studio 17 2022"

    - name: Build
      run: |
        cmake --build cmake-build-debug --config Debug

    - name: Run Tests
      run: |
        .\cmake-build-debug\PolygonLabelEncoderTests.exe