name: C++ CI

on:
  push:
    branches:
      - J3113_Konkova_Nina
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest -Uri https://github.com/Kitware/CMake/releases/latest/download/cmake-*-win64-x64.msi -OutFile cmake.msi
        Start-Process msiexec.exe -ArgumentList '/i cmake.msi /quiet /norestart' -NoNewWindow -Wait
        Remove-Item cmake.msi

    - name: Install Ninja
      run: |
        # Скачиваем и распаковываем Ninja
        Invoke-WebRequest -Uri https://github.com/ninja-build/ninja/releases/latest/download/ninja-win.zip -OutFile ninja.zip
        Expand-Archive ninja.zip -DestinationPath $Env:ProgramFiles
        Remove-Item ninja.zip
        $env:Path += ";$Env:ProgramFiles\ninja-win"

    - name: Configure and Build with CMake
      run: |
        cmake -S . -B cmake-build-debug -G Ninja
        cmake --build cmake-build-debug

    - name: Run PolygonLabelEncoderTests
      run: .\cmake-build-debug\PolygonLabelEncoderTests.exe